### ISSUE TITLE
need method or property to get cpu time

### ISSUE THREAD

**Issue by martinpitt** [larskarlitski/libvirt-dbus#3]
Cockpit currently uses `virsh domstats` to get the VM's current `cpu.time` to measure CPU utilization relative to realtime. This is not currently exposed in libvirt-dbus. I think the corresponding API is [virDomainGetInfo()](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetInfo). This also provides `memory` and `maxMem`, which might be cheaper to get this way (just one call) rather than through `GetStats()`.

**Comment by Antique** [comment]
This is not required, the cpu.time is provided via [virDomainListGetStats()](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainListGetStats), the dbus method is domain.GetStats. The ultimate goal of GetStats is to provide you all information via one API call instead of using several APIs.

If this is sufficient please close the issue :).

**Comment by larskarlitski** [comment]
Ya, `GetDomainInfo()` looked like an old, non-extensible API to me. That's why I didn't include it.

`GetStats()` gives you `vcpu.0.time` and such. Is that enough? If not, adding `GetInfo` is a simple patch and I'd be happy to include it,

**Comment by martinpitt** [comment]
Oh, vpcu.time.0, I see. Thanks!
