### ISSUE TITLE
don't stringify states

### ISSUE THREAD

**Issue by martinpitt** [larskarlitski/libvirt-dbus#4]
The `State` property is currently a string, with some rather made-up values like "shutoff". `virsh` e. g. calls that "shut off", so it's not quite compatible with the current cockpit UI.

It might be better to just expose the [virDomainState](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainState) as a plain uint, which might also help with autogenerating the interface.

**Comment by larskarlitski** [comment]
The idea was to use the last part of the enum, lower case, so that it reads a bit more friendly and can be autogenerated as well. I didn't know that `virsh` uses different names.

Another argument for this is that we're passing in flags and such into some methods already, so people will have to deal with random integers and consult the docs anyway.

@Antique, what are your thoughts?

**Comment by Antique** [comment]
The original idea is not ideal but it gives you some readable string. I guess that we can simply use the uint.

In addition we could expose a method which would return array of pairs (name, uint) as replacement for enums. This way the code using dbus binding could use these arrays instead of magic numbers or redefining all the enums.

**Comment by larskarlitski** [comment]
> The original idea is not ideal but it gives you some readable string. I guess that we can simply use the uint.

Right. I'm still in favor of strings (we now have them in other signals as well) to minimize the amount of magic numbers in client code. I'm ok changing it though if you and @martinpitt  feel strongly about it.

> In addition we could expose a method which would return array of pairs (name, uint) as replacement for enums. This way the code using dbus binding could use these arrays instead of magic numbers or redefining all the enums.

We don't typically put utility functions on D-Bus. It seems pointless to add an IPC round trip for static information.

**Comment by martinpitt** [comment]
I don't have a strong opinion about it. It seemed to me that using ints would make libvirt-dbus and autogeneration easier; if these values are being used somewhere else where ints are impractical, then of course by all means keep it as strings. I. e. I'm happy to close this, but wanted to discuss it first.

**Comment by larskarlitski** [comment]
Ok, I'm leaving it as is then, until we run into further issues down the line.
